### ISSUE TITLE
Error when click on "Open PowerToys Settings"

### ISSUE THREAD

**Issue by Galedrim** [PederBirk/Flow.Launcher.Plugin.PowerToys#1]
Flow Launcher version: 1.19.1

Exception:

```
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\paulj\AppData\Local\PowerToys\PowerToys.exe' with working directory 'C:\Users\paulj\AppData\Local\FlowLauncher\app-1.19.1'. Le fichier spécifié est introuvable.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Plugin.PowerToys.OpenPowerToysSettingsAction.Execute()
   at Flow.Launcher.Plugin.PowerToys.PowerToys.<>c__DisplayClass4_0.<MapActionToResult>b__0(ActionContext _)
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsyrnc>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
PowerToys is installed at C:\Program Files\PowerToys for me, but Flow Launcher seems to be trying to find it at a different path (C:\Users\paulj\AppData\Local\PowerToys\PowerToys.exe).

Could you please resolve this?

Thanks!

**Comment by PederBirk** [comment]
fixed in #6
